# Project: Project2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = 이름없음2.o $(RES)
LINKOBJ  = 이름없음2.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/OpenCV2.2/lib" -lopencv_calib3d220 -lopencv_contrib220 -lopencv_core220 -lopencv_features2d220 -lopencv_ffmpeg220 -lopencv_flann220 -lopencv_gpu220 -lopencv_highgui220 -lopencv_imgproc220 -lopencv_legacy220 -lopencv_ml220 -lopencv_objdetect220 -Gdi32.lib -mwindows  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/OpenCV2.2/include"  -I"C:/OpenCV2.2/include/opencv" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/OpenCV2.2/include"  -I"C:/OpenCV2.2/include/opencv" 
BIN  = Project2.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project2.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Project2.exe" $(LIBS)

이름없음2.o: 이름없음2.c
	$(CC) -c 이름없음2.c -o 이름없음2.o $(CFLAGS)
